---
grails:
    profile: web
    codegen:
        defaultPackage: apikey
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
server:
    tomcat:
        port-header: 'X-Forwarded-Port'
        protocol-header: 'X-Forwarded-Proto'
        remote-ip-header: 'X-Forwarded-For'
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
---
skin:
    layout: main
    orgNameLong: Atlas of Living Australia
    orgNameShort: ALA

security:
    cas:
        uriFilterPattern: /testAuth.*,/upload.*,/getKey/submit,/app/addAnApp

environments:
    development:
        security:
            cas:
                appServerName: http://devt.ala.org.au:8080
        grails:
            logging:
                jul:
                    usebridge: true
    test:
        security:
                cas:
                    appServerName: http://devt.ala.org.au:8080
    production:
        security:
                cas:
                    appServerName: http://auth.ala.org.au
        grails:
            logging:
                jul:
                    usebridge: false
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username:
    password:
    properties:
        timeBetweenEvictionRunsMillis: 60000 # milliseconds (default = 5000)
        testOnBorrow: true # default = false
        testOnReturn: false # default = false
        testWhileIdle: true # default = false
        validationQuery: /* ping */ SELECT 1
        validationQueryTimeout: 10 //seconds (default = -1 i.e. disabled)
        removeAbandoned: true # # default = false
        removeAbandonedTimeout: 300 # seconds (default = 60)
        logAbandoned: true # adds some overhead to every borrow from the pool, disable if it becomes a performance issue

# environment specific settings
environments:
    development:
        dataSource:
            dbCreate: update
            url: "jdbc:mysql://localhost:3306/apikey"
    test:
        dataSource:
            dbCreate: update
            driverClassName: org.h2.Driver
            username: sa
            password: ""
            url: "jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000"
    production:
        dataSource:
            dbCreate: none
