---
grails:
    profile: web
    codegen:
        defaultPackage: apikey
    config:
        locations:
            - file:/data/apikey/config/apikey-config.properties
            - file:/data/apikey/config/apikey-config.yml
            - file:/data/apikey/config/apikey-config.groovy
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    session:
        store-type: none
        disable-redis-config-action: false
server:
  use-forward-headers: true
  tomcat:
    remote_ip_header: x-forwarded-for
    port-header: x-forwarded-port
    protocol_header: x-forwarded-proto
    protocol-header-https-value: https
    # Add IPv6 localhost to default list
    internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
---
flyway:
    enabled: true
    baselineOnMigrate: true
    baselineVersion: 1
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    cache:
        enabled: true
        ehcache:
            cacheManagerName: 'apikey-cache-manager'
            ehcacheXmlLocation: 'classpath:apikey-ehcache.xml'
            reloadable: false
endpoints:
    jmx:
        unique-names: true
---
skin:
    layout: "ala-main"
    fluidLayout: false
    orgNameLong: "Atlas of Living Australia"
    orgNameShort: "ALA"
userdetails:
  url: https://auth.ala.org.au/userdetails

security:
    cas:
        uriFilterPattern: "/testAuth.*,/upload.*,/getKey/submit,/app/addAnApp,/apiKey.*"
        authenticateOnlyIfLoggedInFilterPattern: "/"
    filterOrder: 0
    basic:
        enabled: true
        authorizeMode: role
        realm: ALA User Details
        path:
          - /status/**
endpoints:
    enabled: false
    sensitive: true
    jmx:
        unique-names: true
    cors:
        allow-credentials: true
        allowed-methods:
          - GET
          - POST
          - DELETE
          - PUT
        allowed-headers: "*"
        allowed-origins: "*"
management:
    context-path: /status
    security:
        enabled: true
        roles: ACTUATOR
spring:
    boot:
        admin:
            client:
                enabled: false
                service-base-url: ${serverURL}
                metadata:
                    user:
                        name: ${security.user.name}
                        password: ${security.user.password}

environments:
    development:
        security:
            cas:
                appServerName: http://devt.ala.org.au:8080
        grails:
            logging:
                jul:
                    usebridge: true
    test:
        security:
                cas:
                    appServerName: http://devt.ala.org.au:8080
    production:
        security:
                cas:
                    appServerName: http://auth.ala.org.au
        grails:
            logging:
                jul:
                    usebridge: false
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSource:
    pooled: true
    jmxExport: true
    type: "com.zaxxer.hikari.HikariDataSource"
    properties:


# environment specific settings
environments:
    development:
        dataSource:
            dbCreate: update
            driverClassName: com.mysql.jdbc.Driver
            url: "jdbc:mysql://localhost:3306/apikey"
    test:
        dataSource:
            dbCreate: update
            driverClassName: org.h2.Driver
            username: sa
            password: ""
            url: "jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000"
    production:
        dataSource:
            dbCreate: none
            driverClassName: com.mysql.jdbc.Driver
